enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  948b2d21-c173-429b-9b01-191e44f58878: # Craftcmsjosh
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
