enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  948b2d21-c173-429b-9b01-191e44f58878: # Craftcmsjosh
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: 'pages/{slug}'
type: channel
